### Práctica 7 - Miembros del gimnasio
@host = http://localhost:3000

### 1. Prueba de método listar() -> 200
GET {{host}}/miembros

### 2. Prueba de método buscar() -> 200
GET {{host}}/miembros/1

### 3. Prueba de método crear() -> 201
POST {{host}}/miembros
Content-Type: application/json

{"nombre": "Rick Sanchez", "correo": "wubbalubbadubdub@gmail.com", "membresia": "premium"}

### 4. Prueba de método actualizar() -> 200
PATCH {{host}}/miembros/2
Content-Type: application/json

{"nombre": "John Marston", "correo": "itsJohnMarstonMicah@gmail.com"}

### 5. Prueba de método eliminar() -> 200
DELETE {{host}}/miembros/3

### EXTRA: Se verifica el cambio de estado de Sofía (miembro con id = 3)
GET {{host}}/miembros
